import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import measuresRouter from "./measures.js";
import shopCategoriesRouter from "./shop-categories.js";
import shopsRouter from "./shops.js";
import settingsRouter from "./settings.js";
import productCategoriesRouter from "./product-categories.js";
import productsRouter from "./products.js";
import customersRouter from "./customers.js";
import salesRouter from "./sales.js";
import saleReturnsRouter from "./sale-returns.js";
import suppliersRouter from "./suppliers.js";
import purchasesRouter from "./purchases.js";
import purchaseReturnsRouter from "./purchase-returns.js";
import inventoryRouter from "./inventory.js";
import transfersRouter from "./transfers.js";
import financeRouter from "./finance.js";
import affiliatesRouter from "./affiliates.js";
import subscriptionsRouter from "./subscriptions.js";
import attendantsRouter from "./attendants.js";
import adminRouter from "./admin.js";
import ordersRouter from "./orders.js";
import communicationsRouter from "./communications.js";
import reportsRouter from "./reports.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/measures", measuresRouter);
router.use("/shop-categories", shopCategoriesRouter);
router.use("/shops", shopsRouter);
router.use("/settings", settingsRouter);
router.use("/product-categories", productCategoriesRouter);
router.use("/products", productsRouter);
router.use("/customers", customersRouter);
router.use("/sales", salesRouter);
router.use("/sale-returns", saleReturnsRouter);
router.use("/suppliers", suppliersRouter);
router.use("/purchases", purchasesRouter);
router.use("/purchase-returns", purchaseReturnsRouter);
router.use("/inventory", inventoryRouter);
router.use("/transfers", transfersRouter);
router.use("/finance", financeRouter);
router.use("/affiliates", affiliatesRouter);
router.use("/subscriptions", subscriptionsRouter);
router.use("/attendants", attendantsRouter);
router.use("/admin", adminRouter);
router.use("/orders", ordersRouter);
router.use("/communications", communicationsRouter);
router.use("/reports", reportsRouter);

export default router;
