// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/designs/DesignA.tsx": () => import("../components/mockups/designs/DesignA.tsx"),
  "./components/mockups/designs/DesignB.tsx": () => import("../components/mockups/designs/DesignB.tsx"),
  "./components/mockups/designs/DesignC.tsx": () => import("../components/mockups/designs/DesignC.tsx")
};
